CertLoginIntroText = "You have presented a valid client certificate for the following email addresses:"
CertLoginRequestText = "Do you want to use this certificate for authentication or do you want to use a different method?"
ErrorEmail = "Please enter a valid email address."
ErrorEmailRequired = "Please enter an email address."
ErrorPasswordRequired = "Please enter a password."
ErrorRequired = "Please enter a value"
ErrorTitle = "An error has occurred"
ErrorUnknown = "Unknown error"
IndexGreeting = "Hello {{ .User }}"
IndexIntroductionText = "This is an authorization protected resource"
IndexTitle = "Welcome to the Demo application"
IntroConsentMoreInformation = "You can find more information about <strong>{{ .client }}</strong> at <a href=\"{{ .clientLink }}\">its description page</a>."
IntroConsentRequested = "The <strong>{{ .client }}</strong> application wants your consent for the requested set of permissions."
LabelConsent = "I hereby agree that the application may get the requested permissions."
LabelSubmit = "Submit"
LoginTitle = "Login"
Scope-email-Description = "Access your primary email address."
Scope-offline_access-Description = "Keep access to your information until you revoke the permission."
Scope-openid-Description = "Request information about your identity."
Scope-profile-Description = "Access your user profile information including your name, birth date and locale."
TitleRequestConsent = "Application requests your consent"
WrongOrLockedUserOrInvalidPassword = "You entered an invalid username or password or your account has been locked."

[FormLabelEmail]
description = "Label for an email form field"
other = "Email:"

[FormLabelPassword]
description = "Label for a password form field"
other = "Password:"

[LabelAcceptCertLogin]
description = "Label for a button to accept certificate login"
other = "Yes, please use the certificate"

[LabelLogin]
description = "Label for a login button"
other = "Login"

[LabelRejectCertLogin]
description = "Label for a button to reject certificate login"
other = "No, please ask for my password"

[LogoutLabel]
description = "A label on a logout button or link"
other = "Logout"
